Add about Rector documentation
laminas/laminas-servicemanager-migration pull request #110
Opened 2023-01-14 08:57 UTC by samsonasik

Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| Documentation | yes

### Description

@froschdesign this is copied from the website https://getrector.org/about

2023-01-16 09:38 UTC, froschdesign commented on docs/book/v1/intro.md
> +Rector is a PHP tool that you can run on any PHP project to get instant upgrade or automated refactoring. It helps with PHP upgrade, framework upgrade and improves your code quality. Also it helps wi
```suggestion
Rector is a console application for automated refactoring of PHP applications.
It helps with:

- PHP upgrades
- Framework upgrades
- Code quality improvements
- Type coverage

For more information about Rector, visit: [getrector.org](https://getrector.org)
```

2023-01-16 11:10 UTC, samsonasik commented
@froschdesign updated 👍

2023-01-16 11:49 UTC, froschdesign commented on docs/book/v1/intro.md
>  # laminas-servicemanager-migration
Navigation entry and title / first headline of the page must be the same:

https://github.com/laminas/laminas-servicemanager-migration/blob/751890e8ac17cb9f806359945845abe6fa02b200/mkdocs.yml#L5

```suggestion
# Introduction
```

2023-01-16 12:16 UTC, froschdesign requested changes
An important information is missing in the introduction:

How can it help with laminas-servicemanager?

2023-01-16 12:27 UTC, samsonasik commented
Yes, that still missing, should probably separate PR for that, per PR description, it only part of #70

2023-01-20 21:43 UTC, samsonasik commented
Let's merge so we have progress

2023-01-20 21:43 UTC, merged

2023-01-20 21:45 UTC, samsonasik commented
@froschdesign thank you for the review.